# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'snabb' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for snabb

  target 'snabbTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
