# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Snabb' do
  use_frameworks!

  target 'SnabbTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
