fastlane_version "1.46.1"

platform :ios do
                
        lane :beta do
            increment_build_number(
              xcodeproj: './ios/snabb.xcodeproj'
            )

            sh("xctool -project ../ios/snabb.xcodeproj -scheme snabb clean archive -archivePath ../build/snabb")

            sh("xcodebuild -exportArchive -exportFormat ipa -archivePath ../build/snabb.xcarchive -exportPath ../build/snabb.ipa -exportProvisioningProfile 'iOS Team Provisioning Profile: *'")

            sh("cp ../build/snabb.ipa $BITRISE_DEPLOY_DIR")
        end

end